export interface InputKey{
    line: number,
    value: string,
    specialKey?: boolean
}
export const KeyboardKeys: InputKey[] = [
    { line: 1, value: '1' },
    { line: 1, value: '2' },
    { line: 1, value: '3' },
    { line: 1, value: '4' },
    { line: 1, value: '5' },
    { line: 1, value: '6' },
    { line: 1, value: '7' },
    { line: 1, value: '8' },
    { line: 1, value: '9' },
    { line: 1, value: '0' },
    { line: 1, value: '⌫', specialKey: true },
    { line: 2, value: 'q' },
    { line: 2, value: 'w' },
    { line: 2, value: 'e' },
    { line: 2, value: 'r' },
    { line: 2, value: 't' },
    { line: 2, value: 'y' },
    { line: 2, value: 'u' },
    { line: 2, value: 'i' },
    { line: 2, value: 'o' },
    { line: 2, value: 'p' },
    { line: 2, value: '↲', specialKey: true },
    { line: 3, value: 'a' },
    { line: 3, value: 's' },
    { line: 3, value: 'd' },
    { line: 3, value: 'f' },
    { line: 3, value: 'g' },
    { line: 3, value: 'h' },
    { line: 3, value: 'j' },
    { line: 3, value: 'k' },
    { line: 3, value: 'l' },
    { line: 3, value: 'ñ' },
    { line: 3, value: '?' },
    { line: 4, value: '⇑', specialKey: true },
    { line: 4, value: 'z' },
    { line: 4, value: 'x' },
    { line: 4, value: 'c' },
    { line: 4, value: 'v' },
    { line: 4, value: 'b' },
    { line: 4, value: 'n' },
    { line: 4, value: 'm' },
    { line: 4, value: ',' },
    { line: 4, value: '.' },
    { line: 4, value: '-' },
    { line: 4, value: '!' },
    { line: 5, value: 'Espacio', specialKey: true },
    { line: 5, value: 'Borrar', specialKey: true },
];

export const DefaultFontSize:number = 24;